### PR TITLE
Partitioning should not overwrite schema

### LINKED ISSUE #1750: [Bug]: Protocol lost using partitioning mechanism whilst uploading to S3
### What happened?

I am currently getting error `Scheme "file://" is not supported by this protocol. Expected scheme is "aws-s3://"` . When attempting to upload to S3 with partitions. @norberttech mentioned it 'seems that there might be a bug in partitioning mechanism when uploading to S3 (seems that it doesn't keep protocol)'.

edit:
Discord thread for context: https://discord.com/channels/1263821077558333451/1389631343305949336

### How to reproduce?

```php
$config = config_builder()
    ->mount(
    aws_s3_filesystem(
        $this->bucketName,
        aws_s3_client(
            [
                'region' => $this->region,
                'accessKeyId' => $this->accessKeyId,
                'accessKeySecret' => $this->accessKeySecret,
            ],
        ),
    ),
);

$frame = data_frame($config)
    ->extract(from_array($dataAsArray))
    ->batchSize(10)
    ->mode(overwrite())
    ->withEntry(
        'year',
        ref('createdAt')->cast('date')->dateFormat('Y'),
    )
    ->withEntry(
        'month',
        ref('createdAt')->cast('date')->dateFormat('m'),
    )
    ->withEntry(
        'day',
        ref('createdAt')->cast('date')->dateFormat('d'),
    )
    ->partitionBy(
        ref('year'),
        ref('month'),
        ref('day'),
    )
    ->map(
        fn(Row $row): Row => $row->remove(ref('year'), ref('month'), ref('day')),
    )
    ->load(to_parquet(path("aws-s3://test.parquet")))
    ->run()
;
```

### Data required to reproduce bug locally

[
     ['createdAt' => '2000-01-13'],
     ['createdAt' => '2012-01-13'],
]

### Version

0.19.*

### Relevant error output

```shell
In Protocol.php line 36:
                                                                                      
  Scheme "file://" is not supported by this protocol. Expected scheme is "aws-s3://"
```

### PR DESCRIPTION
**Pull request by stloyd**
Resolves: #1750

Added new (in fact, it's a copy of the existing filesystem stream) filesystem with a custom scheme to confirm that the protocol is lost when partitioning is done.

<h2>Change Log</h2>
<hr /> 
<div id="change-log">
  <h4>Added</h4>
  <ul id="added">
    
  </ul> 
  <h4>Fixed</h4>  
  <ul id="fixed">
    <li>Partitioning should not overwrite schema</li>
  </ul>
  <h4>Changed</h4>
  <ul id="changed">
    
  </ul>  
  <h4>Removed</h4>
  <ul id="removed">
    
  </ul>
  <h4>Deprecated</h4>
  <ul id="deprecated">
    
  </ul>  
  <h4>Security</h4> 
  <ul id="security">
    
  </ul>     
</div>

### CODE REVIEW

File: src/core/etl/tests/Flow/ETL/Tests/Integration/Filesystem/FilesystemStreams/Partitioned/OverwriteModeTest.php [hunk 1]
```diff
@@ -85,6 +86,29 @@ public function test_open_stream_for_non_existing_partition() : void
         self::assertSame('new content', \file_get_contents($files[0]->path->path()));
     }
 
+    public function test_open_stream_for_non_existing_partition_with_custom_schema() : void
+    {
+        $this->setupFiles([__FUNCTION__ => []]);
+
+        $fs = new FakeNativeLocalFilesystem();
```
Comment (norberttech) [inline src/core/etl/tests/Flow/ETL/Tests/Integration/Filesystem/FilesystemStreams/Partitioned/OverwriteModeTest.php:93]: could this be replaced with `src/lib/filesystem/src/Flow/Filesystem/Local/MemoryFilesystem.php` maybe? I'm not sure how I feel about Fake Filesystem in ETL package

File: src/core/etl/src/Flow/ETL/Filesystem/FilesystemStreams.php [hunk 2]
```diff
@@ -38,14 +36,13 @@ public function closeStreams(Path $path) : void
...
                 foreach ($nextStreams as $fileStream) {
-
                     if ($fileStream->isOpen()) {
                         $fileStream->close();
                     }
 
                     if ($this->saveMode === SaveMode::Overwrite) {
                         if ($fileStream->path()->partitions()->count()) {
-                            $partitionFilesPatter = new Path($fileStream->path()->parentDirectory()->path() . '/*', $fileStream->path()->options());
+                            $partitionFilesPatter = new Path($fileStream->path()->parentDirectory()->uri() . '/*', $fileStream->path()->options());
```
Comment (norberttech) [inline src/core/etl/src/Flow/ETL/Filesystem/FilesystemStreams.php:45]: 👌

File: src/core/etl/tests/Flow/ETL/Tests/Integration/Filesystem/FilesystemStreams/Partitioned/OverwriteModeTest.php (hunk 1 above)
Comment (stloyd) [reply src/core/etl/tests/Flow/ETL/Tests/Integration/Filesystem/FilesystemStreams/Partitioned/OverwriteModeTest.php:93]: Memory doesn't support `mv()` method, so it will unfortunately not help :(

Comment (stloyd) [reply src/core/etl/tests/Flow/ETL/Tests/Integration/Filesystem/FilesystemStreams/Partitioned/OverwriteModeTest.php:93]: We could create a dummy to log action calls, if that copy is a problem.

Comment (norberttech) [reply src/core/etl/tests/Flow/ETL/Tests/Integration/Filesystem/FilesystemStreams/Partitioned/OverwriteModeTest.php:93]: yeah, I tried before merging, ended up moving this double to Filesystem package
