### PR TITLE
[GoogleSheet] Skip empty rows at the beginning of a sheet

### LINKED ISSUE #1828: [Bug]: Empty rows considered as header in Google Loader
### What happened?

In rare cases, when a Google Sheet contains an empty row at begging it will be parsed as a header, leading to the skipping of the whole sheet.

Example: https://docs.google.com/spreadsheets/d/1GzB5mEc7FPf8p_RFcUSuANtwtAB5OwOxLMwd2OV7mo0/edit

### How to reproduce?

```php
$extractor = new GoogleSheetExtractor(
            'https://docs.google.com/spreadsheets/d/1GzB5mEc7FPf8p_RFcUSuANtwtAB5OwOxLMwd2OV7mo0/edit',
            '1234567890',
            new Columns('Sheet', 'A', 'Z'),
        );

        $rows = $extractor->extract(flow_context(config()));
```

### Data required to reproduce bug locally

Google Sheet loader

### Version

0.22

### Relevant error output

```shell
No error, just empty result.
```

### PR DESCRIPTION
**Pull request by stloyd**
Resolves: #1828

<h2>Change Log</h2>
<hr /> 
<div id="change-log">
  <h4>Added</h4>
  <ul id="added">
    
  </ul> 
  <h4>Fixed</h4>  
  <ul id="fixed">
    <li>[GoogleSheet] Skip empty rows at the beginning of a sheet</li>
  </ul>
  <h4>Changed</h4>
  <ul id="changed">
    
  </ul>  
  <h4>Removed</h4>
  <ul id="removed">
    
  </ul>
  <h4>Deprecated</h4>
  <ul id="deprecated">
    
  </ul>  
  <h4>Security</h4> 
  <ul id="security">
    
  </ul>     
</div>

### CODE REVIEW

File: src/adapter/etl-adapter-google-sheet/src/Flow/ETL/Adapter/GoogleSheet/GoogleSheetExtractor.php [hunk 1]
```diff
@@ -50,20 +50,31 @@ public function extract(FlowContext $context) : \Generator
...
-            /** @var array<string> $headers */
-            $headers = $values[0];
-            unset($values[0]);
-            $totalRows = 1;
-        } else {
-            $totalRows = 0;
+            foreach ($values as $index => $row) {
+                if ([] === $row) {
+                    // Remove empty rows at the beginning of a sheet
+                    unset($values[$index]);
```
Comment (norberttech) [inline src/adapter/etl-adapter-google-sheet/src/Flow/ETL/Adapter/GoogleSheet/GoogleSheetExtractor.php:59]: hmm wont that remove any empty row, regardless of the position in the sheet? Like for example one in the middle?

Comment (stloyd) [reply src/adapter/etl-adapter-google-sheet/src/Flow/ETL/Adapter/GoogleSheet/GoogleSheetExtractor.php:59]: No cause there is a `break;` after assign of first found data, so it will remove just first rows till any data found.

Comment (norberttech) [reply src/adapter/etl-adapter-google-sheet/src/Flow/ETL/Adapter/GoogleSheet/GoogleSheetExtractor.php:59]: oh right 👍

**Review by norberttech — APPROVED** [review]
