### PR TITLE
Move JSON & Uuid validation out of `StringTypeNarrower`

### LINKED ISSUE #1952: [Proposal]: Move type validation into types from other places
### Describe the Proposal

While working on #1912 and a bit on #1927, I noticed that validation rules for type and entries are not stored in one place, i.e.:
- json is in `StringTypeChecker::isJson()`,
- `type_json->isValid()` calls internally: `StringTypeChecker::isJson()`,
- UUID is in `StringTypeChecker::isUuid()` but regex is in `Uuid` value object,
- HTML is in an `HTMLDocument` value object,

This introduces some inconsistency, as `UuidEntry::withValue()` will work only with `Uuid` VO, even though `UuidEntry` accepts strings. This is because `TypeDetector` uses only strict validation on entries, whereas `EntryFactory` is based on both `TypeDetector` & `StringTypeChecker`.

### API Adjustments

Adjust method in `Type::isValid()` interface and related types to hold the real validation of what they are inside of the types.

Change type methods like `StringTypeChecker::isJson()` and to something like:
```diff
Subject: [PATCH] Move validation to types
---
Index: src/lib/types/src/Flow/Types/Type/Logical/JsonType.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/lib/types/src/Flow/Types/Type/Logical/JsonType.php b/src/lib/types/src/Flow/Types/Type/Logical/JsonType.php
--- a/src/lib/types/src/Flow/Types/Type/Logical/JsonType.php	(revision d18f6af36e318061500eefad0d1f9bb4c86e9164)
+++ b/src/lib/types/src/Flow/Types/Type/Logical/JsonType.php	(date 1762173380920)
@@ -46,7 +46,30 @@
             return false;
         }
 
-        return (new StringTypeChecker($value))->isJson();
+        if ($value === '') {
+            return false;
+        }
+
+        if ('{' !== $value[0] && '[' !== $value[0]) {
+            return false;
+        }
+
+        if (\function_exists('json_validate')) {
+            return \json_validate($value);
+        }
+
+        if (
+            (!\str_starts_with($value, '{') || !\str_ends_with($value, '}'))
+            && (!\str_starts_with($value, '[') || !\str_ends_with($value, ']'))
+        ) {
+            return false;
+        }
+
+        try {
+            return \is_array(\json_decode($value, true, flags: \JSON_THROW_ON_ERROR));
+        } catch (\Exception) {
+            return false;
+        }
     }
 
     public function normalize() : array
Index: src/lib/types/src/Flow/Types/Type/Native/String/StringTypeChecker.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/lib/types/src/Flow/Types/Type/Native/String/StringTypeChecker.php b/src/lib/types/src/Flow/Types/Type/Native/String/StringTypeChecker.php
--- a/src/lib/types/src/Flow/Types/Type/Native/String/StringTypeChecker.php	(revision d18f6af36e318061500eefad0d1f9bb4c86e9164)
+++ b/src/lib/types/src/Flow/Types/Type/Native/String/StringTypeChecker.php	(date 1762173380925)
@@ -5,6 +5,7 @@
 namespace Flow\Types\Type\Native\String;
 
 use Flow\Types\Value\{HTMLDocument, Uuid};
+use function Flow\Types\DSL\type_json;
 
 final readonly class StringTypeChecker
 {
@@ -123,30 +124,7 @@
 
     public function isJson() : bool
     {
-        if ($this->string === '') {
-            return false;
-        }
-
-        if ('{' !== $this->string[0] && '[' !== $this->string[0]) {
-            return false;
-        }
-
-        if (\function_exists('json_validate')) {
-            return \json_validate($this->string);
-        }
-
-        if (
-            (!\str_starts_with($this->string, '{') || !\str_ends_with($this->string, '}'))
-            && (!\str_starts_with($this->string, '[') || !\str_ends_with($this->string, ']'))
-        ) {
-            return false;
-        }
-
-        try {
-            return \is_array(\json_decode($this->string, true, flags: \JSON_THROW_ON_ERROR));
-        } catch (\Exception) {
-            return false;
-        }
+        return type_json()->isValid($this->string);
     }
 
     public function isNull() : bool

```

### Are you intending to also work on proposed change?

Yes

### Are you interested in sponsoring this change?

No

### Integration & Dependencies

_No response_

### PR DESCRIPTION
**Pull request by stloyd**
Resolves: #1952

<h2>Change Log</h2>
<hr /> 
<div id="change-log">
  <h4>Added</h4>
  <ul id="added">
    
  </ul> 
  <h4>Fixed</h4>  
  <ul id="fixed">
    
  </ul>
  <h4>Changed</h4>
  <ul id="changed">
    <li>Move JSON & Uuid validation out of `StringTypeNarrower`</li>
  </ul>  
  <h4>Removed</h4>
  <ul id="removed">
    
  </ul>
  <h4>Deprecated</h4>
  <ul id="deprecated">
    
  </ul>  
  <h4>Security</h4> 
  <ul id="security">
    
  </ul>     
</div>

### CODE REVIEW

**Review by norberttech — CHANGES_REQUESTED** [review]
Not whole json validation is covered with unit tests (that's why CI/CD complains)

Also please look at who is assigned to a task/issue 😅 this one was actually assigned to @MrHDOLEK

File: src/lib/types/src/Flow/Types/Type/Logical/JsonType.php [hunk 1]
```diff
@@ -46,7 +45,30 @@ public function isValid(mixed $value) : bool
...
+
+        if (\function_exists('json_validate')) {
+            return \json_validate($value);
+        }
+
+        try {
+            return \is_array(\json_decode($value, true, flags: \JSON_THROW_ON_ERROR));
+        } catch (\JsonException) {
+            return false;
+        }
```
Comment (stloyd) [inline src/lib/types/src/Flow/Types/Type/Logical/JsonType.php]: Testing this part would require removing the package `symfony/polyfill-php83`, cause it provides the above function.

File: src/lib/types/src/Flow/Types/Value/Uuid.php [hunk 2]
```diff
@@ -28,11 +28,13 @@ public function __construct(string|UuidInterface|\Symfony\Component\Uid\Uuid $va
                     $this->value = (string) \Ramsey\Uuid\Uuid::fromString($value);
                 } elseif (\class_exists(\Symfony\Component\Uid\Uuid::class)) {
                     $this->value = \Symfony\Component\Uid\Uuid::fromString($value)->toRfc4122();
-                } else {
+                } elseif (\strlen($value) !== 36 && 1 !== \preg_match(self::UUID_REGEXP, $value)) {
```
Comment (stloyd) [inline src/lib/types/src/Flow/Types/Value/Uuid.php]: Similarly, it would require the removal of both Symfony and Ramsey libraries to test this if statement.

File: src/lib/types/src/Flow/Types/Type/Logical/JsonType.php (hunk 1 above)
Comment (norberttech) [reply src/lib/types/src/Flow/Types/Type/Logical/JsonType.php]: we can also make symfony/polyfill-83 a dependency of Flow and simply get rid of this code. It will anyway get removed with support for php8.5 as 8.3 would become the minimum version in few months. O think it's fair tradeoff in this case 

Another polyfill I want to add is mbstring that would remove the need of having mbstring extension

Comment (stloyd) [reply src/lib/types/src/Flow/Types/Type/Logical/JsonType.php]: Added polyfill.

**Comment by norberttech** [comment]
Sweet <3
