### PR TITLE
[Http] Add Http adapter functions

### LINKED ISSUE #1910: [Bug]: Missing Http adapter helper functions
### What happened?

All other adapters seem to have helper functions like `from_*` (`from_xml`), the Http Adapter lacks those.

### How to reproduce?

```php
Try to use some Http adpater helper methods.
```

### Data required to reproduce bug locally

n/a

### Version

0.26

### Relevant error output

```shell
N/a
```

### PR DESCRIPTION
**Pull request by stloyd**
Resolves: #1910

<h2>Change Log</h2>
<hr /> 
<div id="change-log">
  <h4>Added</h4>
  <ul id="added">
    <li>Added missing Http adapter functions</li>
  </ul> 
  <h4>Fixed</h4>  
  <ul id="fixed">
    <li>Avro & Excel added to DSL documentation</li>
  </ul>
  <h4>Changed</h4>
  <ul id="changed">
    
  </ul>  
  <h4>Removed</h4>
  <ul id="removed">
    
  </ul>
  <h4>Deprecated</h4>
  <ul id="deprecated">
    
  </ul>  
  <h4>Security</h4> 
  <ul id="security">
    
  </ul>     
</div>

### CODE REVIEW

File: src/adapter/etl-adapter-http/src/Flow/ETL/Adapter/Http/DSL/functions.php [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+        $client,
+        $requestFactory,
+    );
+}
+
+/**
+ * @param iterable<RequestInterface> $requests
+ */
+#[DocumentationDSL(module: Module::HTTP, type: Type::EXTRACTOR)]
+function from_static_http_client(
```
Comment (norberttech) [inline src/adapter/etl-adapter-http/src/Flow/ETL/Adapter/Http/DSL/functions.php]: technically speaking this is extraction from static http requests using client, so I would probably call it `from_static_http_requests` and the other one `from_dynamic_http_requests`. 
It's because client is just a transport, we are extracting data from `requests`

**Comment by norberttech** [comment]
Since now those extractors are getting DSL functions you also need to add them to `rector.tests.php` so rector can replace `new PsrHttpClientStaticExtractor` with `from_static_http_requests`

**Review by norberttech — APPROVED** [review]
Good to merge after static analysis get fixed 👍

**Comment by stloyd** [comment]
@norberttech seems to be ready, for some reason, mutation fails to detect tests.

**Comment by norberttech** [comment]
> @norberttech seems to be ready, for some reason, mutation fails to detect tests.

I believe it's cache related and recent upgrade of infection - should stabilize soon, but if not will take a look into this later
