### PR TITLE
Fixed reading multine strings in CSV files

### LINKED ISSUE #1738: [Bug]: Reading CSV with multiline strings
### What happened?

Reading CSV files with multiline strings inside of them will fail currently. 
The problem comes from here: https://github.com/flow-php/flow/blob/1.x/src/adapter/etl-adapter-csv/src/Flow/ETL/Adapter/CSV/CSVExtractor.php#L56

### How to reproduce?

```php
df()->read(from_csv(__DIR__.'/dataset.csv'))->write(to_output())->run();
```

### Data required to reproduce bug locally

```csv
"artist","song","link","text"
"ABBA","Ahe's My Kind Of Girl","/a/abba/ahes+my+kind+of+girl_20598417.html","Look at her face, it's a wonderful face  
And it means something special to me  
Look at the way that she smiles when she sees me  
How lucky can one fellow be?  
  
She's just my kind of girl, she makes me feel fine  
Who could ever believe that she could be mine?  
She's just my kind of girl, without her I'm blue  
And if she ever leaves me what could I do, what could I do?  
  
And when we go for a walk in the park  
And she holds me and squeezes my hand  
We'll go on walking for hours and talking  
About all the things that we plan  
  
She's just my kind of girl, she makes me feel fine  
Who could ever believe that she could be mine?  
She's just my kind of girl, without her I'm blue  
And if she ever leaves me what could I do, what could I do?

"
```

### Version

0.19.0

### Relevant error output

```shell
Text row is going to be cut to `Look at her face, it's a wonderful face`
```

### PR DESCRIPTION
**Pull request by norberttech**
Resolves: #1738

<h2>Change Log</h2>
<hr /> 
<div id="change-log">
  <h4>Added</h4>
  <ul id="added">
    
  </ul> 
  <h4>Fixed</h4>  
  <ul id="fixed">
    <li>reading multiline strings in CSV files</li>
  </ul>
  <h4>Changed</h4>
  <ul id="changed">
    
  </ul>  
  <h4>Removed</h4>
  <ul id="removed">
    
  </ul>
  <h4>Deprecated</h4>
  <ul id="deprecated">
    
  </ul>  
  <h4>Security</h4> 
  <ul id="security">
    
  </ul>     
</div>

### CODE REVIEW

File: src/adapter/etl-adapter-csv/src/Flow/ETL/Adapter/CSV/CSVExtractor.php [hunk 1]
```diff
@@ -215,4 +211,34 @@ private function mapHeaders(array $headers) : array
...
     }
+
+    /**
+     * @param array<int, null|string> $rowData
+     *
+     * @return array<int, null|string>
+     */
+    private function normalizeRowData(array $rowData, int $headersCount) : array
+    {
+        $rowDataCount = \count($rowData);
```
Comment (stloyd) [inline src/adapter/etl-adapter-csv/src/Flow/ETL/Adapter/CSV/CSVExtractor.php]: We already have this count at line 62, and it seems `$rowData` is not manipulated after that line. Can't we use it here?

File: src/adapter/etl-adapter-csv/src/Flow/ETL/Adapter/CSV/CSVLineReader.php [hunk 2]
```diff
@@ -0,0 +1,92 @@
...
+    public function readLines(SourceStream $stream) : \Generator
+    {
+        $lineNumber = 0;
+        $buffer = '';
+
+        foreach ($stream->readLines(length: $this->charactersReadInLine) as $rawLine) {
+            $buffer .= $rawLine;
+
+            if (!\str_contains($buffer, $this->enclosure)) {
+                yield $this->removeBOM && $lineNumber === 0 ? $this->removeBOMFromLine(\rtrim($buffer, "\r\n")) : rtrim($buffer, "\r\n");
```
Comment (stloyd) [inline src/adapter/etl-adapter-csv/src/Flow/ETL/Adapter/CSV/CSVLineReader.php:33]: Shouldn't the BOM check be only on line zero? There is no point in repeating the check on every line, no?

File: src/adapter/etl-adapter-csv/src/Flow/ETL/Adapter/CSV/CSVLineReader.php [hunk 3]
```diff
@@ -0,0 +1,92 @@
...
+                    $lineNumber++;
+                    $buffer = '';
+                } else {
+                    $buffer .= "\n";
+                }
+            }
+        }
+
+        if ($buffer !== '') {
+            yield $this->removeBOM && $lineNumber === 0 ? $this->removeBOMFromLine(\rtrim($buffer, "\r\n")) : \rtrim($buffer, "\r\n");
```
Comment (stloyd) [inline src/adapter/etl-adapter-csv/src/Flow/ETL/Adapter/CSV/CSVLineReader.php:48]: Something like this, probably:
```suggestion
        foreach ($stream->readLines(length: $this->charactersReadInLine) as $rawLine) {
            if ($this->removeBOM && $lineNumber === 0) {
                $rawLine = $this->removeBOMFromLine($rawLine);
            }

            $buffer .= $rawLine;

            if (!\str_contains($buffer, $this->enclosure)) {
                yield rtrim($buffer, "\r\n");
                $lineNumber++;
                $buffer = '';
            } else {
                if ($this->isCompleteCSVRecord($buffer)) {
                    yield \rtrim($buffer, "\r\n");
                    $lineNumber++;
                    $buffer = '';
                } else {
                    $buffer .= "\n";
                }
            }
        }

        if ($buffer !== '') {
            yield \rtrim($buffer, "\r\n");
```

File: src/adapter/etl-adapter-csv/src/Flow/ETL/Adapter/CSV/CSVExtractor.php (hunk 1 above)
Comment (norberttech) [reply src/adapter/etl-adapter-csv/src/Flow/ETL/Adapter/CSV/CSVExtractor.php]: I'm actually going to extract this logic to standalone class that can be properly unit tested

File: src/adapter/etl-adapter-csv/src/Flow/ETL/Adapter/CSV/CSVLineReader.php (hunk 2 above)
Comment (stloyd) [reply src/adapter/etl-adapter-csv/src/Flow/ETL/Adapter/CSV/CSVLineReader.php:33]: See [this comment](https://github.com/flow-php/flow/pull/1740/files#r2172169383).

Comment (norberttech) [reply src/adapter/etl-adapter-csv/src/Flow/ETL/Adapter/CSV/CSVLineReader.php:33]: that's how it works now, it checks if `removeBOM` is needed and if it's needed then it checks if the line number is 0 (first line).

File: src/adapter/etl-adapter-csv/src/Flow/ETL/Adapter/CSV/CSVLineReader.php (hunk 3 above)
Comment (norberttech) [reply src/adapter/etl-adapter-csv/src/Flow/ETL/Adapter/CSV/CSVLineReader.php:48]: yeah but line number is not going to be incremented until it's full line, so at the end of the day if the first line contains multi line string, remove BOM will be executed as many times as many lines that multiline string has
