### PR TITLE
Casting XML to string

### LINKED ISSUE #1472: Doctrine Insert with XmlEntry
Hi

If i try and insert a dataframe into a database that contains an XmlEntry, I get the following error:

```
Error: Object of class DOMDocument could not be converted to string

/var/www/html/zg/vendor/doctrine/dbal/src/Driver/PDO/Statement.php:48
/var/www/html/zg/vendor/doctrine/dbal/src/Connection.php:1809
/var/www/html/zg/vendor/doctrine/dbal/src/Connection.php:1205
/var/www/html/zg/vendor/doctrine/dbal/src/Connections/PrimaryReadReplicaConnection.php:292
/var/www/html/zg/vendor/flow-php/doctrine-dbal-bulk/src/Flow/Doctrine/Bulk/Bulk.php:42
/var/www/html/zg/vendor/flow-php/etl-adapter-doctrine/src/Flow/ETL/Adapter/Doctrine/DbalLoader.php:67
/var/www/html/zg/vendor/flow-php/etl/src/Flow/ETL/Pipeline/SynchronousPipeline.php:65
/var/www/html/zg/vendor/flow-php/etl/src/Flow/ETL/DataFrame.php:763
```

Some pseduo code

```sample.json
{"descriptionHtml": "<b>This is a test</b>"}
```

```
       return data_frame()
            ->read(from_json_lines("sample.json")
            ->write(to_dbal_table_insert(.....)
```

I had a quick look at submitting a fix, as I managed to hack the v0.10.0 code to get it to work, however looks like I need a postgress db to run the test-suite which i don't currently have installed, and i suspect this is already fixed or easy enough for you.

I believe you need to handle it here

https://github.com/flow-php/flow/blob/dfde1cc8238a42281f77a60f44851052ca34c885/src/lib/doctrine-dbal-bulk/src/Flow/Doctrine/Bulk/BulkData.php#L137

I believe something like this
```
\DOMDocument::class => $entry->saveXML($entry->documentElement),
```

As i side note are they are workarounds you can think of to transform the datatype in the row?

Closest I got was
```
->withEntry('DESCRIPTION_HTML', ref('DESCRIPTION_HTML')->domElementValue())
```
But that strips out the html tags, which ideally i want to keep.

### PR DESCRIPTION
**Pull request by norberttech**
<h2>Change Log</h2>
<div id="change-log">
  <h4>Added</h4>
  <ul id="added">
    <li>Early detection of XML type in dbal bulk</li>
  </ul> 
  <h4>Fixed</h4>  
  <ul id="fixed">
    <li>Incosistency between XMLEntry::toString and Casting XML's to strings</li>
  </ul>
  <h4>Changed</h4>
  <ul id="changed">
    
  </ul>  
  <h4>Removed</h4>
  <ul id="removed">
    
  </ul>
  <h4>Deprecated</h4>
  <ul id="deprecated">
    
  </ul>  
  <h4>Security</h4> 
  <ul id="security">
    
  </ul>     
</div>
<hr/>

<h2>Description</h2>

Resolves: #1472

### CODE REVIEW

**Comment by norberttech** [comment]
ping @jmortlock

File: src/lib/doctrine-dbal-bulk/src/Flow/Doctrine/Bulk/BulkData.php [hunk 1]
```diff
@@ -143,6 +144,16 @@ public function toSqlParameters(TableDefinition $table) : array
                             Types::DATETIME_IMMUTABLE => \DateTimeImmutable::createFromMutable($entry),
                             default => $entry,
                         },
+                        \DOMDocument::class => match (Type::getTypeRegistry()->lookupName($table->dbalColumn($column)->getType())) {
+                            Types::TEXT,
+                            Types::STRING => $entry->saveXML($entry->documentElement),
+                            default => $entry,
+                        },
+                        \DOMElement::class => match (Type::getTypeRegistry()->lookupName($table->dbalColumn($column)->getType())) {
```
Comment (norberttech) [inline src/lib/doctrine-dbal-bulk/src/Flow/Doctrine/Bulk/BulkData.php:152]: @jmortlock I followed your suggestion, this requires a bigger refactoring, it's not perfect but it works, and it works well so I'm keeping it for now. Ideally I would like to extract that logic to a different place but that requires some planning and I'm a bit short on time currently

Comment (jmortlock) [reply src/lib/doctrine-dbal-bulk/src/Flow/Doctrine/Bulk/BulkData.php:152]: Works for me

**Review by jmortlock — COMMENTED** [review]
LGTM, thanks for getting this resolved.
